// ============================================================
// CATÁLOGO DE PRODUCTOS
// Este es el ÚNICO archivo que tenés que tocar para agregar,
// sacar o modificar productos. No hace falta saber programar,
// solo seguir el mismo patrón que ya está.
//
// Estructura general:
//   CATALOG es una lista de CATEGORÍAS.
//   Cada categoría tiene: n (número), title (nombre que se ve
//   en el menú) e items (lista de productos de esa categoría).
//
// Cada PRODUCTO tiene estos campos (todos entre comillas ""):
//   key         -> identificador único, sin espacios ni tildes
//                  (ej: "anua-rice-serum"). No se repite entre productos.
//   name        -> nombre que ve el cliente.
//   size        -> tamaño/presentación (ej: "50 ml", "1 unidad").
//   price       -> precio mayorista en pesos, SIN puntos ni comas (ej: 15000).
//   retail      -> (opcional) precio de venta sugerido al público, para
//                  calcular la rentabilidad en la sección "Calculá tu
//                  ganancia". Si no lo ponés, ese producto simplemente
//                  no suma al cálculo de rentabilidad.
//   img         -> ruta a la foto principal, dentro de la carpeta
//                  images/ (ej: "images/mi-producto.jpg").
//   images      -> (opcional) lista de fotos extra para la galería
//                  del panel de detalle. Si no la ponés, se usa
//                  solo "img".
//   benefit     -> texto de "Beneficio".
//   skin        -> texto de "Tipo de piel".
//   ingredients -> texto de "Ingredientes".
//   modo        -> texto de "Modo de uso".
//
// Para AGREGAR un producto: copiá una línea { ... } entera de un
// producto parecido, pegala donde quieras dentro de la misma
// categoría (entre los [ ] de "items"), y cambiá los datos.
// No te olvides de subir también la foto a la carpeta images/
// con el mismo nombre que pusiste en "img".
//
// Para AGREGAR una categoría nueva: copiá un bloque completo
// { n:"..", title:"..", items:[ ... ] }, pegalo antes del ]
// final, y cambiále el número y el título.
//
// Ojo con la sintaxis: cada producto va entre { } separado por
// comas, y cada categoría también. Si algo se rompe, probablemente
// falte o sobre una coma o una llave — fijate en el producto de
// al lado para copiar el mismo patrón exacto.
// ============================================================

const CATALOG = [
{ n:"01", title:"Mascarillas faciales", items:[
  {key:"biodance-radiant-vita", name:"Biodance Radiant Vita Niacinamide Real Deep Mask", size:"1 unidad", price:7550, retail:12000, img:"images/biodance-radiant-vita.jpg", images:["images/biodance-radiant-vita-1.jpg","images/biodance-radiant-vita-2.jpg"], benefit:"Ilumina el rostro, unifica el tono de la piel e hidrata profundamente.", skin:"Piel especialmente opaca, con manchas o tono desigual.", ingredients:"Fabricada con un suero solidificado que se vuelve transparente a medida que la piel absorbe los nutrientes.", modo:"De día, luego de preparar la piel con tónico o suero, aplicar la mascarilla y dejar actuar 3-4hrs o hasta que se vuelva totalmente transparente. De noche, es el último paso de tu rutina, dejándola actuar mientras dormís. Enjuagá por la mañana."},
  {key:"biodance-refreshing-sea", name:"Biodance Refreshing Sea Kelp Real Deep Mask", size:"1 unidad", price:7800, retail:12000, img:"images/biodance-refreshing-sea.jpg", benefit:"Calma, purifica y equilibra la piel.", skin:"Efectiva para pieles grasas, con acné o sensibles.", ingredients:"Fabricada con un suero solidificado que se vuelve transparente a medida que la piel absorbe los nutrientes.", modo:"De día, luego de preparar la piel con tónico o suero, aplicar la mascarilla y dejar actuar 3-4hrs o hasta que se vuelva totalmente transparente. De noche, es el último paso de tu rutina, dejándola actuar mientras dormís. Enjuagá por la mañana."},
  {key:"biodance-bio-collagen", name:"Biodance Bio-Collagen Real Deep Mask", size:"1 unidad", price:8600, retail:12000, img:"images/biodance-bio-collagen.jpg", benefit:"Mejora la firmeza y elasticidad, minimiza la apariencia de los poros, fortalece la barrera cutánea e hidrata para un efecto glass skin.", skin:"Todo tipo de piel, especialmente seca, deshidratada o con pérdida de firmeza.", ingredients:"Fabricada con un suero solidificado que se vuelve transparente a medida que la piel absorbe los nutrientes.", modo:"De día, luego de preparar la piel con tónico o suero, aplicar la mascarilla y dejar actuar 3-4hrs o hasta que se vuelva totalmente transparente. De noche, es el último paso de tu rutina, dejándola actuar mientras dormís. Enjuagá por la mañana."},
  {key:"torriden-balanceful", name:"Torriden Balanceful Mask", size:"1 unidad", price:5650, retail:9000, img:"images/torriden-balanceful.jpg", benefit:"Mascarilla de tela con centella asiática que calma, hidrata y refresca la piel.", skin:"Piel sensible, mixta, grasa, normal y con tendencia acneica o al enrojecimiento.", ingredients:"Extracto de Centella Asiática, complejo Cica, ácido hialurónico, pantenol y alantoína.", modo:"Aplicar sobre el rostro limpio, dejar actuar de 15 a 20 minutos, retirar y masajear la esencia restante hasta su absorción, sin enjuagar."},
  {key:"torriden-dive-in", name:"Torriden Dive-In Mask", size:"1 unidad", price:5650, retail:9000, img:"images/torriden-dive-in.jpg", benefit:"Mascarilla facial hidratante que aporta suavidad, elasticidad y luminosidad a la piel.", skin:"Piel seca, normal, mixta, grasa y deshidratada.", ingredients:"Ácido hialurónico de bajo peso molecular, pantenol, alantoína, ceramidas y betaína.", modo:"Aplicar sobre el rostro limpio, dejar actuar de 15 a 20 minutos, retirar y masajear la esencia restante hasta su absorción, sin enjuagar."},
  {key:"torriden-cellmazing", name:"Torriden Cellmazing Brightening Mask", size:"1 unidad", price:5600, retail:9000, img:"images/torriden-cellmazing.jpg", benefit:"Mascarilla facial iluminadora que unifica el tono y aporta luminosidad a la piel.", skin:"Piel normal, mixta, grasa, seca y opaca.", ingredients:"Vitamina C, niacinamida, pantenol, alantoína y ácido hialurónico.", modo:"Aplicar sobre el rostro limpio, dejar actuar de 15 a 20 minutos, retirar y masajear la esencia restante hasta su absorción, sin enjuagar."},
  {key:"medicube-pdrn-pink-collagen-gel-mask", name:"Medicube PDRN Pink Collagen Gel Mask", size:"1 unidad", price:7600, retail:12000, img:"images/medicube-pdrn-pink-collagen-gel-mask.jpg", benefit:"Mejora la elasticidad, hidratación y luminosidad de la piel.", skin:"Ideal para piel seca, normal, mixta o deshidratada.", ingredients:"PDRN, colágeno hidrolizado, niacinamida y péptidos.", modo:"Durante la noche o de 3 a 4hrs durante el día, hasta que el parche quede transparente."},
  {key:"medicube-kojic-turmeric-mask", name:"Medicube Kojic Acid Turmeric Brightening Gel Mask", size:"1 unidad", price:7500, retail:12000, img:"images/medicube-kojic-turmeric-mask.jpg", benefit:"Efecto 'glass skin'. Hidratación intensa y reducción de la pigmentación.", skin:"Ideal para todo tipo de piel, especialmente piel opaca o con manchas.", ingredients:"Ácido kójico, cúrcuma, niacinamida y extracto de raíz de cúrcuma.", modo:""},
  {key:"medicube-zero-pore-blackhead-mud-mask", name:"Medicube Zero Pore Blackhead Mud Mask", size:"100 gr", price:24550, retail:45000, img:"images/medicube-zero-pore-blackhead-mud-mask.jpg", benefit:"Mascarilla de arcilla de acción rápida diseñada para limpiar profundamente los poros, reducir puntos negros y controlar el exceso de grasa, dejando la piel más lisa y uniforme.", skin:"Pieles mixtas, grasas, con poros visibles o puntos negros.", ingredients:"Ácidos exfoliantes (glicólico, salicílico y PHA). Libre de alcohol, fragancias fuertes y parabenos.", modo:"Aplicar sobre piel limpia y seca. Dejar actuar 3-5 min. Enjuagar con agua tibia. Se recomienda usarla 1-2 veces por semana."},
  {key:"medicube-collagen-night-mask", name:"Medicube Collagen Night Mask", size:"75 gr", price:18400, retail:45000, img:"images/medicube-collagen-night-mask.jpg", benefit:"Mejora la firmeza y elasticidad, hidrata intensamente, calma la piel y la deja suave, luminosa y con una textura más uniforme gracias al colágeno, los péptidos, las ceramidas y el alga chlorella.", skin:"Apta para pieles sensibles y maduras.", ingredients:"Extracto de colágeno, niacinamida, ácido hialurónico, ceramida NP y extracto de alga chlorella.", modo:"Último paso de la rutina nocturna. Aplicar una capa uniforme sobre el rostro limpio y seco. Dejar secar 15 min hasta formar una película delgada. Dormí con la mascarilla puesta y retirala a la mañana con agua tibia."},
  {key:"anua-heartleaf-enzyme-pore-clay-mask", name:"Anua Heartleaf + Enzyme Pore Clay Pack Mask", size:"100 gr", price:19900, retail:40000, img:"images/anua-heartleaf-enzyme-pore-clay-mask.jpg", benefit:"Purifica los poros, absorbe el exceso de grasa y calma la piel irritada mediante una suave exfoliación enzimática.", skin:"", ingredients:"Houttuynia cordata (controla sebo y calma irritación), enzimas (suaviza textura de piel), bentonita y caolín (desintoxica poros), colágeno soluble y péptidos (mantienen elasticidad de poros).", modo:""},
  {key:"medicube-pdrn-caffeine-night-wrapping-mask", name:"Medicube PDRN Pink Caffeine Night Wrapping Mask", size:"75 gr", price:18450, retail:45000, img:"images/medicube-pdrn-caffeine-night-wrapping-mask.jpg", benefit:"Mascarilla facial nocturna que hidrata, revitaliza y mejora la luminosidad de la piel mientras dormís, dejando un aspecto más firme y saludable al despertar.", skin:"Piel normal, seca, mixta, grasa y opaca.", ingredients:"PDRN (Sodium DNA), cafeína, niacinamida, ácido hialurónico y pantenol.", modo:"Aplicar una capa uniforme sobre el rostro limpio como último paso de la rutina nocturna, dejar actuar toda la noche y retirar o enjuagar por la mañana."},
  {key:"medicube-pdrn-sleeping-lip-mask", name:"Medicube PDRN Sleeping Lip Mask", size:"15 gr", price:18200, retail:33000, img:"images/medicube-pdrn-sleeping-lip-mask.jpg", benefit:"Hidrata profundamente, mejora la elasticidad y el volumen de los labios, dejando un acabado brillante natural y no pegajoso. Su textura jelly cremosa se funde al aplicarla, creando una capa nutritiva que repara labios secos, agrietados o con textura irregular durante toda la noche.", skin:"Apta para todo tipo de piel, especialmente piel seca, opaca o con pérdida de firmeza.", ingredients:"PDRN (ADN de salmón), colágeno, niacinamida, ceramidas y ácido hialurónico.", modo:"Aplicar una cantidad adecuada sobre el rostro limpio como último paso de la rutina, mañana y/o noche."},
]},
{ n:"02", title:"Limpiadores faciales", items:[
  {key:"anua-heartleaf-pore-control-cleansing-oil", name:"Anua Heartleaf Pore Control Cleansing Oil", size:"200 ml", price:23200, retail:40000, img:"images/anua-heartleaf-pore-control-cleansing-oil.jpg", benefit:"Elimina maquillaje y protector solar mientras calma y purifica la piel con extracto de heartleaf, gracias a su textura ligera que no deja sensación oleosa ni obstruye los poros.", skin:"Ideal para pieles sensibles o con poros congestionados.", ingredients:"Propiedades calmantes, antibacterianas y seborreguladoras.", modo:"Aplicar sobre el rostro seco con las manos secas, masajear suavemente para disolver el maquillaje e impurezas, emulsionar con un poco de agua y enjuagar con abundante agua tibia."},
  {key:"axisy-quinoa-cleanser", name:"AXIS-Y Quinoa One-Step Balanced Gel Cleanser", size:"180 ml", price:26250, retail:45000, img:"images/axisy-quinoa-cleanser.jpg", benefit:"Gel limpiador facial de pH balanceado que elimina maquillaje, impurezas y exceso de grasa sin resecar la piel, dejándola limpia y fresca.", skin:"Ideal para piel normal, seca, mixta, grasa y sensible.", ingredients:"Extracto de quinoa, centella asiática, caléndula, té verde, regaliz y alantoína.", modo:"Aplicar una pequeña cantidad sobre el rostro húmedo, masajear suavemente con movimientos circulares y enjuagar con abundante agua."},
  {key:"anua-heartleaf-bha-cleansing-foam", name:"Anua Heartleaf BHA Pore Deep Cleansing Foam", size:"150 ml", price:19500, retail:39000, img:"images/anua-heartleaf-bha-cleansing-foam.jpg", benefit:"Espuma limpiadora facial de acción profunda que limpia impurezas, exceso de sebo y residuos acumulados en los poros sin resecar la piel.", skin:"Ideal para pieles mixtas, grasas y sensibles con tendencia al acné.", ingredients:"Heartleaf, ácido salicílico, quercetinol, ácido hialurónico y glicerina.", modo:"Aplicar sobre el rostro húmedo, masajear suavemente y enjuagar con agua."},
  {key:"anua-rice-enzyme-cleansing-powder", name:"Anua Rice Enzyme Cleansing Powder", size:"40 gr", price:29700, retail:45000, img:"images/anua-rice-enzyme-cleansing-powder.jpg", benefit:"Limpiador facial en polvo. Al contacto con el agua se transforma en una espuma ligera que elimina impurezas y células muertas sin dañar la barrera de la piel, dejando el rostro suave, uniforme y con efecto glow natural.", skin:"Ideal para pieles sensibles o con tendencia a brotes.", ingredients:"Extracto de arroz, enzimas de papaína y ceramidas.", modo:"Mezclar una pequeña cantidad con agua hasta formar espuma, masajear sobre el rostro y enjuagar."},
  {key:"medicube-pdrn-hydrating-gel-cleanser", name:"Medicube PDRN Hydrating Gel Cleanser", size:"200 ml", price:34600, retail:60000, img:"images/medicube-pdrn-hydrating-gel-cleanser.jpg", benefit:"Limpia profundamente sin resecar, ayuda a reparar la barrera cutánea y deja una sensación fresca y flexible.", skin:"Ideal para pieles secas o irritadas.", ingredients:"PDRN (ADN de salmón), ácido hialurónico, glicerina y pantenol.", modo:""},
  {key:"medicube-red-foam-cleanser", name:"Medicube Red Foam Cleanser", size:"120 ml", price:22450, retail:39000, img:"images/medicube-red-foam-cleanser.jpg", benefit:"Limpia profundamente los poros, elimina maquillaje e impurezas, calma la piel y ayuda a controlar el exceso de sebo sin resecar.", skin:"Ideal para pieles mixtas, grasas y sensibles.", ingredients:"Ácido salicílico (BHA), glicerina, extractos botánicos y agentes limpiadores suaves.", modo:"Aplicar sobre el rostro húmedo, masajear hasta formar espuma y enjuagar con agua."},
  {key:"medicube-zero-pore-cleansing-oil", name:"Medicube Zero Pore Blackhead Deep Cleansing Oil", size:"200 ml", price:30150, retail:60000, img:"images/medicube-zero-pore-cleansing-oil.jpg", benefit:"Elimina maquillaje, el exceso de sebo y los puntos negros persistentes. Contribuye a una piel más clara y suave.", skin:"Ideal para piel mixta, grasa y con tendencia al acné.", ingredients:"Aceite de salvado de arroz, aceite de jojoba, ácido salicílico (BHA), niacinamida y AHA.", modo:""},
  {key:"skin1004-centella-poremizing-cleansing-foam", name:"Skin1004 Centella Poremizing Cleansing Foam", size:"125 ml", price:18000, retail:33000, img:"images/skin1004-centella-poremizing-cleansing-foam.jpg", benefit:"Limpia impurezas, minimiza la apariencia de los poros y calma la piel sin resecar.", skin:"Ideal para pieles grasas y sensibles.", ingredients:"Extracto de centella asiática, caolín, sal rosa del Himalaya y glicerina.", modo:"Aplicar sobre el rostro húmedo, masajear hasta formar espuma y enjuagar."},
  {key:"skin1004-centella-teatrica-bha-foam", name:"Skin1004 Centella Tea-Trica BHA Foam", size:"125 ml", price:16900, retail:33000, img:"images/skin1004-centella-teatrica-bha-foam.jpg", benefit:"Limpiador espumoso. Elimina impurezas y el exceso de sebo sin resecar, dejando la piel calmada y fresca.", skin:"Ideal para pieles grasas, sensibles o con tendencia al acné.", ingredients:"Centella asiática, árbol de té, BHA (ácido salicílico) y pantenol.", modo:"Aplicar sobre el rostro húmedo, masajear hasta formar espuma y enjuagar."},
  {key:"skin1004-centella-ampoule-foam", name:"Skin1004 Centella Ampoule Foam", size:"125 ml", price:16950, retail:33000, img:"images/skin1004-centella-ampoule-foam.jpg", benefit:"Limpiador espumoso. Ofrece una limpieza profunda, suave y calmante. Elimina impurezas, sebo y maquillaje, manteniendo un pH equilibrado sin resecar.", skin:"Ideal para pieles sensibles, mixtas o grasas.", ingredients:"Extracto de centella asiática, bicarbonato de sodio, glicerina y ácido cítrico.", modo:""},
]},
{ n:"03", title:"Tónicos y toner pads", items:[
  {key:"biodance-sea-kelp-toner", name:"Biodance Sea Kelp Gel Toner", size:"60 pads · 140 gr", price:28600, retail:49000, img:"images/biodance-sea-kelp-toner.jpg", benefit:"Extracto fermentado de algas marinas para calmar. Hidrata con mar rica en minerales, ayuda a controlar el sebo y equilibrar el pH de la piel. Mejora la calidad de la piel y reduce la visibilidad de las imperfecciones.", skin:"Ideal para pieles sensibles y propensas al acné.", ingredients:"Alga marina (Sea Kelp), agua de mar profunda, pantenol y extractos calmantes.", modo:"Pasar un pad sobre el rostro limpio o dejar actuar unos minutos como mascarilla."},
  {key:"biodance-vita-niacinamide-toner", name:"Biodance Vita Niacinamide Gel Toner", size:"60 pads · 140 gr", price:28650, retail:49000, img:"images/biodance-vita-niacinamide-toner.jpg", benefit:"Fórmula con niacinamida, agua de piña y glutatión que unifica el tono y la textura de la piel, mientras proporciona una tez radiante.", skin:"Todo tipo de piel, especialmente opaca o con manchas.", ingredients:"Niacinamida, glutatión, agua de piña y ácido hialurónico.", modo:""},
  {key:"biodance-ceranol-toner", name:"Biodance Cera-Nol Gel Toner", size:"60 pads · 140 gr", price:29350, retail:49000, img:"images/biodance-ceranol-toner.jpg", benefit:"Mezcla de D-Pantenol, ceramidas y 10 capas de ácido hialurónico que calma, hidrata y reduce la rojez. Ayuda a calmar rojeces e irritaciones físicas y químicas causadas por calor o exposición al sol.", skin:"Ideal para pieles sensibles o irritadas.", ingredients:"Ceramidas, D-Pantenol, ácido hialurónico, alantoína y extractos calmantes.", modo:"Después de la limpieza, pasar un pad sobre el rostro o dejarlo actuar unos minutos como mascarilla en las zonas que necesiten mayor hidratación. No enjuagar."},
  {key:"biodance-collagen-toner", name:"Biodance Collagen Gel Toner", size:"60 pads · 140 gr", price:29450, retail:49000, img:"images/biodance-collagen-toner.jpg", benefit:"Formulado con colágeno, ácido hialurónico y galactomyces que ayudan a reducir la apariencia de los poros, mejorar la elasticidad de la piel y unificar el tono.", skin:"Ideal para pieles sensibles y con falta de firmeza.", ingredients:"Colágeno de bajo peso molecular, ácido hialurónico, pantenol, ceramidas y alantoína.", modo:""},
  {key:"anua-heartleaf-soothing-toner", name:"Anua Heartleaf Soothing Toner", size:"250 ml", price:23100, retail:39000, img:"images/anua-heartleaf-soothing-toner.jpg", benefit:"Calmante y refrescante que equilibra la piel. Alivia molestias mientras prepara la piel para absorber mejor los siguientes pasos de la rutina facial.", skin:"Ideal para pieles sensibles, irritadas o con tendencia a enrojecimiento.", ingredients:"77% de extracto de heartleaf (Houttuynia Cordata), ácido hialurónico, betaína, pantenol y glicerina.", modo:"Después de la limpieza, aplicar con un algodón o directamente con las manos sobre el rostro. Dar suaves toques hasta su completa absorción."},
  {key:"anua-heartleaf-clear-pads", name:"Anua Heartleaf Clear Pads", size:"70 pads · 160 ml", price:28800, retail:42000, img:"images/anua-heartleaf-clear-pads.jpg", benefit:"Pads que purifican, controlan el exceso de sebo, calman la piel y ofrecen una suave exfoliación mientras tonifican e hidratan.", skin:"Ideal para pieles sensibles por su exfoliante químico que ayuda a eliminar células muertas.", ingredients:"77% de extracto de heartleaf (Houttuynia Cordata), PHA, ácido hialurónico, pantenol y betaína.", modo:"Después de la limpieza, pasar primero el lado texturizado y luego el lado liso sobre el rostro. No enjuagar."},
  {key:"medicube-zero-pore-pads", name:"Medicube Zero Pore Pads", size:"70 pads · 155 gr", price:28800, retail:49000, img:"images/medicube-zero-pore-pads.jpg", benefit:"Pads exfoliantes que ayudan a minimizar la apariencia de los poros, controlar el exceso de sebo y suavizar la textura de la piel sin resecar.", skin:"Piel mixta, grasa, con poros dilatados o tendencia al acné.", ingredients:"AHA, BHA, pantenol, alantoína e hialuronato de sodio.", modo:"Después de la limpieza, pasar un pad sobre el rostro evitando el contorno de ojos. No enjuagar y continuar con la rutina de cuidado facial."},
  {key:"medicube-pdrn-niacinamide-milky-toner", name:"Medicube PDRN Pink Niacinamide Milky Toner", size:"150 ml", price:28700, retail:49000, img:"images/medicube-pdrn-niacinamide-milky-toner.jpg", benefit:"Tónico de rápida absorción con PDRN y niacinamida que hidrata, ilumina, unifica el tono y fortalece la barrera cutánea para un efecto glass skin.", skin:"Ideal para pieles secas, apagadas o sensibles.", ingredients:"PDRN de salmón, niacinamida, ceramida NP, pantenol y ácido hialurónico.", modo:"Después de la limpieza, aplicar con las manos o un algodón sobre el rostro y dar suaves toques hasta su completa absorción."},
  {key:"anua-peach77-niacin-essence-toner", name:"Anua Peach 77% Niacin Essence Toner", size:"250 ml", price:28650, retail:49000, img:"images/anua-peach77-niacin-essence-toner.jpg", benefit:"Tónico con esencia que hidrata, ilumina y mejora la textura para una piel suave y luminosa.", skin:"Para todo tipo de pieles.", ingredients:"Extracto de durazno (77%), niacinamida, ceramidas fermentadas y ácido hialurónico.", modo:"Aplicar después de la limpieza con las manos o un algodón y dar suaves toques hasta su absorción."},
  {key:"anua-rice-milky-toner", name:"Anua Rice Milky Toner", size:"250 ml", price:28450, retail:49000, img:"images/anua-rice-milky-toner.jpg", benefit:"Tónico lechoso que hidrata, ilumina y fortalece la barrera cutánea, dejando la piel suave y con un brillo natural.", skin:"Para todo tipo de pieles.", ingredients:"Agua de salvado de arroz (70%), ceramidas, niacinamida, pantenol y ácido hialurónico.", modo:"Aplicar después de la limpieza con las manos o un algodón y dar suaves toques hasta su completa absorción."},
  {key:"mediheal-madecassoside-pads", name:"Mediheal Madecassoside Blemish Pads", size:"100 pads · 170 ml", price:37250, retail:59000, img:"images/mediheal-madecassoside-pads.jpg", benefit:"Pads faciales calmantes impregnados en esencia, diseñados para calmar la piel, reducir rojeces y mejorar imperfecciones mientras hidratan y fortalecen la barrera cutánea.", skin:"Ideal para pieles sensibles, mixtas, con rojeces y tendencia a imperfecciones.", ingredients:"Madecassoside (24%), centella asiática, pantenol, alantoína y ácido hialurónico.", modo:"Después de la limpieza, pasar un pad suavemente por el rostro evitando el contorno de ojos. También puede usarse como mascarilla localizada durante 5-10 minutos."},
  {key:"mediheal-vitamide-pads", name:"Mediheal Vitamide Brightening Pads", size:"100 pads · 170 ml", price:36650, retail:59000, img:"images/mediheal-vitamide-pads.jpg", benefit:"Rico en vitamina C, aporta luminosidad a la vez que ayuda a combatir las imperfecciones.", skin:"Todo tipo de piel, especialmente opaca, con manchas o tono desigual.", ingredients:"Complejo Vitamide (vitaminas), niacinamida, pantenol, alantoína y ácido hialurónico.", modo:""},
  {key:"skin1004-madagascar-poremizing-toner", name:"Skin1004 Centella Madagascar Poremizing Toner", size:"210 ml", price:19200, retail:35000, img:"images/skin1004-madagascar-poremizing-toner.jpg", benefit:"Exfoliante y purificante formulado con Centella Asiática de Madagascar y complejo 4-HA (AHA, BHA, PHA y LHA), diseñado para limpiar profundamente los poros, controlar el exceso de sebo y mejorar la textura de la piel.", skin:"Ideal para pieles mixtas, grasas, con poros visibles y textura irregular.", ingredients:"Centella asiática de Madagascar, sal rosa del Himalaya, AHA, PHA, pantenol y ácido hialurónico.", modo:""},
  {key:"skin1004-madagascar-teatrica-purifying-toner", name:"Skin1004 Centella Madagascar Tea-Trica Purifying Toner", size:"210 ml", price:18650, retail:35000, img:"images/skin1004-madagascar-teatrica-purifying-toner.jpg", benefit:"Tónico facial purificante que ayuda a equilibrar el exceso de grasa, calmar la piel y mantener los poros limpios, dejando una sensación de frescura.", skin:"Para piel grasa, mixta, con tendencia acneica y sensible.", ingredients:"Extracto de Centella Asiática, agua de árbol de té, complejo Tea-Trica, niacinamida y ácido salicílico (BHA).", modo:"Aplicar una cantidad adecuada sobre un algodón o directamente con las manos sobre el rostro limpio, dando suaves toques hasta su completa absorción."},
  {key:"skin1004-madagascar-hyalucica-toner", name:"Skin1004 Centella Madagascar Hyalu-Cica Toner", size:"210 ml", price:19250, retail:35000, img:"images/skin1004-madagascar-hyalucica-toner.jpg", benefit:"Hidratante y calmante que combina Centella Asiática de Madagascar con ácido hialurónico, diseñado para hidratar en profundidad, calmar la piel y reforzar la barrera cutánea.", skin:"Ideal para pieles que necesitan hidratación constante sin saturarse.", ingredients:"Centella asiática de Madagascar, complejo Hyalu-Cica (ácido hialurónico + centella), niacinamida, ceramidas y pantenol.", modo:""},
  {key:"skin1004-madagascar-toning-toner", name:"Skin1004 Centella Madagascar Toning Toner", size:"210 ml", price:19500, retail:35000, img:"images/skin1004-madagascar-toning-toner.jpg", benefit:"Tónico exfoliante suave. Hidrata, calma la irritación y mejora la textura al eliminar células muertas, dejando la piel radiante y equilibrada.", skin:"Ideal para pieles sensibles.", ingredients:"Centella asiática de Madagascar, PHA (gluconolactona), niacinamida, ácido hialurónico y pantenol.", modo:"Aplicar una cantidad adecuada sobre un algodón o directamente con las manos sobre el rostro limpio, dando suaves toques hasta su completa absorción."},
  {key:"roundlab-dokdo-toner", name:"Round Lab 1025 Dokdo Toner", size:"200 ml", price:17150, retail:30000, img:"images/roundlab-dokdo-toner.jpg", benefit:"Textura acuosa ultra ligera, formulado con agua de mar profunda rica en minerales. Ayuda a hidratar, calmar y equilibrar la piel sin dejar sensación pesada. Elimina suavemente células muertas, dejando la piel fresca, suave y revitalizada.", skin:"Ideal para pieles sensibles, deshidratadas y mixtas.", ingredients:"Agua de mar profunda (magnesio, calcio, zinc), pantenol, alantoína, betaína y protease (enzima).", modo:"Aplicar después de la limpieza con las manos o un algodón y distribuir suavemente sobre el rostro hasta su completa absorción."},
  {key:"axisy-darkspot-glow-toner", name:"AXIS-Y Dark Spot Correcting Glow Toner", size:"125 ml", price:27100, retail:49000, img:"images/axisy-darkspot-glow-toner.jpg", benefit:"Tónico facial iluminador que ayuda a hidratar, unificar el tono de la piel y reducir la apariencia de manchas, dejando un acabado radiante y saludable.", skin:"Para piel normal, seca, mixta, grasa y con manchas o tono desigual.", ingredients:"Glutatión, niacinamida al 5%, ácido hialurónico, extracto de corteza de sauce blanco y pantenol.", modo:"Aplicar una cantidad adecuada sobre el rostro limpio con las manos o un algodón, dando suaves toques hasta su completa absorción."},
]},
{ n:"04", title:"Serums", items:[
  {key:"medicube-zeropore-oneday-pack", name:"Medicube Zero Pore One-Day Pack ×2", size:"30 ml", price:34800, retail:65000, img:"images/medicube-zeropore-oneday-pack.jpg", benefit:"Minimiza los poros, exfolia suavemente y mejora la textura de la piel con una limpieza profunda.", skin:"Para todo tipo de pieles, especialmente con poros dilatados y puntos negros.", ingredients:"AHA, BHA, PHA, niacinamida, pantenol y ácido hialurónico.", modo:""},
  {key:"medicube-exosome-shot-pore-serum", name:"Medicube One Day Exosome Shot Pore Serum", size:"30 ml", price:27250, retail:45000, img:"images/medicube-exosome-shot-pore-serum.jpg", benefit:"Revitaliza la piel, mejora la firmeza, unifica el tono y minimiza los poros sin sensación pegajosa.", skin:"Para pieles grasas, mixtas, con poros dilatados, puntos negros o acné leve.", ingredients:"Exosomas, niacinamida, PDRN, péptidos y ácido hialurónico.", modo:""},
  {key:"medicube-pink-pdrn-oneday-serum", name:"Medicube Pink PDRN One Day Serum", size:"10 ampollas · 15 ml", price:21800, retail:40000, img:"images/medicube-pink-pdrn-oneday-serum.jpg", benefit:"Proporciona luminosidad e hidratación. Piel fresca y radiante, sin sensación pegajosa.", skin:"Para todo tipo de piel.", ingredients:"PDRN (ADN de salmón), niacinamida, ácido hialurónico, colágeno y pantenol.", modo:""},
  {key:"anua-peach70-niacin-serum", name:"Anua Peach 70% Niacin Serum", size:"30 ml", price:19100, retail:39000, img:"images/anua-peach70-niacin-serum.jpg", benefit:"Actúa sobre los signos visibles de la hiperpigmentación, ayudando a reducir manchas oscuras, controlar el exceso de sebo y mejorar la textura de la piel. Ilumina el rostro, unifica el tono y deja la piel más suave y equilibrada.", skin:"Ideal para pieles apagadas y con manchas.", ingredients:"Niacinamida, ácido tranexámico, Zinc PCA, pantenol, betaína y extracto de centella asiática.", modo:"Aplicar unas gotas sobre el rostro limpio y masajear hasta su absorción."},
  {key:"skin1004-madagascar-ampoule", name:"Skin1004 Centella Madagascar Ampoule", size:"100 ml", price:21200, retail:39000, img:"images/skin1004-madagascar-ampoule.jpg", benefit:"Hidrata profundamente, fortalece la barrera cutánea y ayuda a reducir rojeces, inflamación y marcas de acné.", skin:"Ideal para pieles sensibles, irritadas o enrojecidas.", ingredients:"Extracto de centella asiática de Madagascar (100%).", modo:""},
  {key:"skin1004-madagascar-hyalucica-100", name:"Skin1004 Centella Madagascar Hyalu-Cica", size:"100 ml", price:21500, retail:39000, img:"images/skin1004-madagascar-hyalucica-100.jpg", benefit:"Combina extracto de centella asiática (calmante) y ácido hialurónico (hidratante) para calmar, hidratar profundamente y reparar la barrera cutánea.", skin:"Ideal para pieles sensibles y secas.", ingredients:"Complejo Hyalu-Cica (ácido hialurónico + centella de Madagascar), niacinamida, ceramidas y pantenol.", modo:""},
  {key:"skin1004-madagascar-teatrica-relief-ampoule", name:"Skin1004 Centella Madagascar Tea-Trica Relief Ampoule", size:"100 ml", price:20700, retail:39000, img:"images/skin1004-madagascar-teatrica-relief-ampoule.jpg", benefit:"Sérum que calma la piel, reduce la inflamación y las rojeces, y controla el exceso de sebo sin obstruir los poros.", skin:"Ideal para pieles propensas al acné, sensibles o grasas.", ingredients:"Centella asiática de Madagascar (55%), agua de árbol de té, agua de pino, complejo Tea-Trica y pantenol.", modo:"Aplicar unas gotas sobre el rostro limpio y masajear hasta su absorción."},
  {key:"skin1004-madagascar-poremizing-fresh-ampoule", name:"Skin1004 Centella Madagascar Poremizing Fresh Ampoule", size:"100 ml", price:21300, retail:39000, img:"images/skin1004-madagascar-poremizing-fresh-ampoule.jpg", benefit:"Suero ligero que minimiza los poros, controla el exceso de grasa y calma la piel mientras aporta hidratación y elasticidad.", skin:"Ideal para pieles mixtas a grasas, hipoalergénico.", ingredients:"Extracto de Centella Asiática de Madagascar, sal rosa del Himalaya y péptidos.", modo:"Aplicar unas gotas sobre el rostro limpio y masajear hasta su absorción."},
  {key:"anua-heartleaf-soothing-ampoule", name:"Anua Heartleaf Soothing Ampoule", size:"30 ml", price:22300, retail:45000, img:"images/anua-heartleaf-soothing-ampoule.jpg", benefit:"Ampolla acuosa con una base de Heartleaf para aliviar la piel reduciendo rojeces y calmando inflamaciones.", skin:"Ideal para pieles con rojeces o acné activo, tirantes o deshidratadas.", ingredients:"80% de extracto de Heartleaf para calmar la irritación, y pantenol para reparar la barrera cutánea, hidratar y proteger.", modo:""},
  {key:"anua-niacinamide10-txa4-serum", name:"Anua Niacinamide 10% + TXA 4% Serum", size:"30 ml", price:21850, retail:39000, img:"images/anua-niacinamide10-txa4-serum.jpg", benefit:"Unifica el tono de la piel, reduce manchas oscuras y mejora visiblemente la luminosidad. Hidrata y fortalece la barrera cutánea.", skin:"Para todo tipo de piel con tono desigual, manchas o rojeces.", ingredients:"10% de niacinamida, 4% de ácido tranexámico y ácido hialurónico.", modo:"Aplicar unas gotas sobre el rostro limpio y masajear hasta su absorción."},
  {key:"anua-7rice-ceramide-serum", name:"Anua 7-Rice Ceramide Hydrating Serum", size:"50 ml", price:28550, retail:49000, img:"images/anua-7rice-ceramide-serum.jpg", benefit:"Hidrata en profundidad, refuerza la barrera cutánea, mejora la textura y luminosidad del rostro. Calma, nutre y protege la piel, sin sensación grasa.", skin:"Ideal para pieles secas, sensibles o con barrera debilitada.", ingredients:"Extracto de arroz, ceramidas, niacinamida y ácido hialurónico.", modo:"Aplicar unas gotas sobre el rostro limpio, preferentemente por la mañana, seguido de protector solar."},
  {key:"anua-green-lemon-vitac20", name:"Anua Green Lemon Vita C 20%", size:"20 ml", price:24550, retail:45000, img:"images/anua-green-lemon-vitac20.jpg", benefit:"Hidrata profundamente, fortalece la barrera cutánea, mejora la textura e ilumina la piel con un acabado radiante y sin sensación grasa.", skin:"Para pieles normales, mixtas, opacas y con manchas.", ingredients:"20% de vitamina C, extracto de limón verde, niacinamida y glutatión.", modo:""},
  {key:"anua-peach70plus-niacin-serum", name:"Anua Peach 70+ Niacin Serum", size:"30 ml", price:19300, retail:39000, img:"images/anua-peach70plus-niacin-serum.jpg", benefit:"Mejora la elasticidad, unifica el tono, reduce manchas y poros visibles, y deja la piel luminosa sin sensación pesada.", skin:"Ideal para uso diario en pieles mixtas o grasas con tono apagado o manchas leves.", ingredients:"70% de extracto de durazno, 5% de niacinamida y ácido hialurónico.", modo:""},
  {key:"anua-azelaic10-hyaluron10", name:"Anua Azelaic Acid 10% + Hyaluron 10%", size:"30 ml", price:21550, retail:39000, img:"images/anua-azelaic10-hyaluron10.jpg", benefit:"Sérum calmante con 10% de ácido azelaico y ácido hialurónico que reduce rojeces, unifica el tono e hidrata la piel.", skin:"Ideal para pieles sensibles, con rojeces, manchas o textura irregular.", ingredients:"10% de ácido azelaico, complejo Hyaluron 10 y pantenol.", modo:""},
  {key:"axisy-spot-difference-treatment", name:"AXIS-Y The Spot Difference Blemish Treatment", size:"15 ml", price:25100, retail:45000, img:"images/axisy-spot-difference-treatment.jpg", benefit:"Tratamiento localizado para granitos que ayuda a reducir imperfecciones, calmar la inflamación y favorecer una piel más uniforme.", skin:"Para piel grasa, mixta, con tendencia acneica y sensible.", ingredients:"4-Terpineol, niacinamida al 2%, AHA, BHA y ceramidas.", modo:"Aplicar una pequeña cantidad directamente sobre la imperfección después de la limpieza y antes de la crema hidratante, dejando que se absorba por completo."},
  {key:"axisy-darkspot-glow-serum", name:"AXIS-Y Dark Spot Correcting Glow Serum", size:"50 ml", price:18400, retail:39000, img:"images/axisy-darkspot-glow-serum.jpg", benefit:"Sérum facial iluminador que ayuda a reducir la apariencia de manchas, unificar el tono de la piel y aportar hidratación para un acabado radiante.", skin:"Para piel normal, seca, mixta, grasa y con manchas o tono desigual.", ingredients:"Niacinamida al 5%, escualano vegetal, extracto de espino amarillo (Hippophae Rhamnoides), extracto de arroz y alantoína.", modo:"Aplicar una pequeña cantidad sobre el rostro limpio después del tónico y masajear suavemente hasta su completa absorción."},
  {key:"medicube-collagen-glow-bubble-serum", name:"Medicube Collagen Glow Bubble Serum", size:"100 ml", price:28250, retail:49000, img:"images/medicube-collagen-glow-bubble-serum.jpg", benefit:"Sérum facial en espuma que hidrata, mejora la elasticidad de la piel y aporta un brillo saludable con una textura ligera y de rápida absorción.", skin:"Para piel normal, seca, mixta, grasa y madura.", ingredients:"Complejo Collagen-11, colágeno hidrolizado, niacinamida, ácido hialurónico y adenosina.", modo:"Aplicar una o dos dosis sobre el rostro limpio después del tónico y masajear suavemente hasta su completa absorción."},
  {key:"medicube-collagen-glow-booster-serum", name:"Medicube Collagen Glow Booster Serum", size:"15 ml", price:27800, retail:49000, img:"images/medicube-collagen-glow-booster-serum.jpg", benefit:"Sérum facial concentrado que hidrata, mejora la firmeza de la piel y aporta luminosidad para un aspecto más suave y revitalizado.", skin:"Para piel normal, seca, mixta, grasa y madura.", ingredients:"Colágeno hidrolizado, complejo Collagen-11, niacinamida, ácido hialurónico y adenosina.", modo:"Aplicar una pequeña cantidad sobre el rostro limpio después del tónico y masajear suavemente hasta su completa absorción."},
  {key:"celimax-noni-ampoule", name:"Celimax Noni Ampoule Calming + Radiance", size:"50 ml", price:24600, retail:49000, img:"images/celimax-noni-ampoule.jpg", benefit:"Ampoule facial que calma, hidrata y aporta luminosidad a la piel, ayudando a fortalecer la barrera cutánea y mejorar su apariencia.", skin:"Para piel normal, seca, mixta, grasa, sensible y opaca.", ingredients:"Extracto de noni, Noni Energy™, pantenol, colágeno y ácido hialurónico.", modo:"Aplicar unas gotas sobre el rostro limpio después del tónico y masajear suavemente hasta su completa absorción."},
]},
{ n:"05", title:"Protectores solares", items:[
  {key:"tocobo-cotton-soft-sunstick", name:"Tocobo Cotton Soft Sun Stick SPF50+ PA++++", size:"19 gr", price:18550, retail:32000, img:"images/tocobo-cotton-soft-sunstick.jpg", benefit:"Acabado suave y mate a lo largo del día. Además, calma la piel y controla la producción de sebo con sus complejos herbales.", skin:"Ideales para pieles grasas, mixtas con brillo o exceso de sebo.", ingredients:"Extracto de algodón, sílice y filtros solares químicos.", modo:"Aplicar directamente sobre el rostro y reaplicar durante el día."},
  {key:"tocobo-cica-cooling-sunstick", name:"Tocobo Cica Cooling Sun Stick SPF50+ PA++++", size:"19 gr", price:18550, retail:32000, img:"images/tocobo-cica-cooling-sunstick.jpg", benefit:"Formulado con complejo de CICA fermentada (Centella Asiática) para dar un efecto refrescante y antiinflamatorio. Fórmula hipoalergénica y libre de parabenos.", skin:"", ingredients:"", modo:""},
  {key:"skin1004-centella-teatrica-sun-milk", name:"Skin1004 Centella Madagascar Tea-Trica Soothing Sun Milk", size:"50 ml", price:19850, retail:39000, img:"images/skin1004-centella-teatrica-sun-milk.jpg", benefit:"Protección solar SPF50+ PA++++ ligera y calmante para pieles sensibles. Textura tipo leche, sin dejar residuos blancos ni sensación pesada.", skin:"Ideal para pieles reactivas o con brotes, grasa, mixta y sensibles.", ingredients:"Centella asiática, extracto de árbol de té y niacinamida.", modo:""},
  {key:"skin1004-airefit-sun-cream", name:"Skin1004 Centella Aire-Fit Sun Cream", size:"50 ml", price:20150, retail:39000, img:"images/skin1004-airefit-sun-cream.jpg", benefit:"Protector solar SPF50+ PA++++ ultraligero que bloquea rayos UV e ilumina el tono de la piel con un acabado mate natural. Humecta y suaviza. Textura ligera.", skin:"Ideal para pieles grasa, mixta, sensibles, con rojeces o acné leve.", ingredients:"Centella asiática, niacinamida y filtros solares UV.", modo:"Aplicar como último paso de la rutina antes de la exposición solar."},
  {key:"medicube-pdrn-toneup-sun-cream", name:"Medicube PDRN Pink Tone-Up Sun Cream ×2", size:"50 ml + 20 ml", price:33400, retail:55000, img:"images/medicube-pdrn-toneup-sun-cream.jpg", benefit:"Protector solar que ilumina la piel, previene arrugas y bloquea rayos UV. Mejora la hidratación. (La caja viene con un bote de 50ml y otro de 20ml)", skin:"Ideal para pieles reactivas o con brotes, grasa, mixta y sensibles.", ingredients:"PDRN, niacinamida y filtros solares UV.", modo:"Aplicar como último paso de la rutina antes de la exposición solar."},
  {key:"roundlab-birchjuice-sunscreen", name:"Round Lab Birch Juice Moisturizing Sunscreen", size:"50 ml", price:18700, retail:34000, img:"images/roundlab-birchjuice-sunscreen.jpg", benefit:"Protector solar con savia de abedul y ácido hialurónico para mantener la piel hidratada y tersa durante todo el día.", skin:"Ideal para pieles sensibles.", ingredients:"Savia de abedul, ácido hialurónico y niacinamida.", modo:""},
  {key:"anua-heartleaf-silky-sun-cream", name:"Anua Heartleaf Silky Moisture Sun Cream", size:"50 ml", price:21750, retail:42000, img:"images/anua-heartleaf-silky-sun-cream.jpg", benefit:"Protector solar facial de textura ligera y sedosa que brinda alta protección SPF50+ PA++++. Su acabado es natural, sin efecto blanco ni grasoso, ideal para uso diario y perfecto como base de maquillaje.", skin:"Ideal para pieles mixta, normal, sensible y pieles deshidratadas.", ingredients:"Extracto de Heartleaf (houttuynia cordata) y pantenol, protege contra los rayos UV.", modo:"Aplicar como último paso de la rutina antes de la exposición solar."},
  {key:"boj-daily-tinted-fluid-sunscreen", name:"Beauty of Joseon Daily Tinted Fluid Sunscreen", size:"50 ml", price:29450, retail:49000, img:"images/boj-daily-tinted-fluid-sunscreen.jpg", benefit:"Protector solar con color tipo skin tint que combina SPF40 + hidratación + cobertura ligera, pensado para un acabado natural y rápido en la rutina diaria. Disponible en tono MP200 y LP110.", skin:"Ideal para pieles grasa, normal y mixta.", ingredients:"Óxido de zinc, extracto de artemisa (Artemisia Capillaris), vitamina E (tocoferol), vitamina C (ascorbil palmitato) y sílice.", modo:"Agitar antes de usar, aplicar una cantidad adecuada como último paso de la rutina de cuidado facial y distribuir uniformemente sobre el rostro antes de la exposición al sol."},
]},
{ n:"06", title:"Cremas hidratantes", items:[
  {key:"medicube-ager-glutathione-glow-cream", name:"Medicube AGE-R Glutathione Glow Capsule Cream", size:"50 ml", price:34800, retail:49000, img:"images/medicube-ager-glutathione-glow-cream.jpg", benefit:"Ilumina, mejora el tono, reafirma e hidrata profundamente.", skin:"Para todo tipo de piel.", ingredients:"Glutatión, niacinamida, ceramidas y péptidos.", modo:""},
  {key:"medicube-red-cream", name:"Medicube Red Cream", size:"50 ml", price:28200, retail:45000, img:"images/medicube-red-cream.jpg", benefit:"Crema que calma la piel, reduce el enrojecimiento y fortalece la barrera cutánea.", skin:"Ideal para piel mixta/grasa, con tendencia a acné o reactiva.", ingredients:"Árbol de té, niacinamida y 19 extractos botánicos.", modo:""},
  {key:"medicube-collagen-jelly-cream", name:"Medicube Collagen Jelly Cream", size:"100 ml", price:32350, retail:55000, img:"images/medicube-collagen-jelly-cream.jpg", benefit:"Crema en gel que aporta firmeza, luminosidad e hidratación profunda.", skin:"Ideal para pieles jóvenes y maduras.", ingredients:"Colágeno, niacinamida, escualano y elastina hidrolizada.", modo:""},
  {key:"medicube-exosome-cica-cream", name:"Medicube Exosome Cica Cream", size:"50 ml", price:19500, retail:39000, img:"images/medicube-exosome-cica-cream.jpg", benefit:"Calma la piel, mejora la textura y controla el exceso de sebo.", skin:"Ideal para todo tipo de piel.", ingredients:"Exosome Cica, ceramidas, ectoína y centella asiática.", modo:"Aplicar como último paso de la rutina sobre el rostro limpio."},
  {key:"medicube-deep-vitac-capsule-cream", name:"Medicube Deep Vita C Capsule Cream", size:"55 gr", price:32450, retail:55000, img:"images/medicube-deep-vitac-capsule-cream.jpg", benefit:"Gel con vitamina C que ilumina, unifica el tono, reduce manchas y aporta glow natural.", skin:"Para todo tipo de piel.", ingredients:"Vitamina C, niacinamida, ácido ferúlico y extracto de espino amarillo.", modo:""},
  {key:"medicube-txa-niacinamide-capsule", name:"Medicube TXA Niacinamide Capsule Cream", size:"55 gr", price:31450, retail:55000, img:"images/medicube-txa-niacinamide-capsule.jpg", benefit:"Crema con cápsulas TXA que unifica el tono, mejora la textura y aporta luminosidad.", skin:"Para todo tipo de piel.", ingredients:"Ácido tranexámico (TXA), niacinamida y cápsulas iluminadoras.", modo:"Aplicar como último paso de la rutina sobre el rostro limpio."},
  {key:"roundlab-birchjuice-cream-80", name:"Round Lab Birch Juice Moisturizing Cream", size:"80 ml", price:25350, retail:45000, img:"images/roundlab-birchjuice-cream-80.jpg", benefit:"Crema hidratante coreana de textura ligera tipo gel que proporciona hidratación profunda y duradera sin sensación pesada, ideal para lograr una piel equilibrada, suave y luminosa.", skin:"Ideal para pieles que necesitan hidratación sin pesadez.", ingredients:"Savia de abedul (birch juice) rica en minerales, aminoácidos y factores naturales de hidratación, ácido hialurónico, pantenol y niacinamida.", modo:"Aplicar como último paso de la rutina sobre el rostro limpio."},
  {key:"roundlab-birchjuice-cream-30", name:"Round Lab Birch Juice Moisturizing Cream", size:"30 ml", price:13800, retail:29000, img:"images/roundlab-birchjuice-cream-30.jpg", benefit:"Crema hidratante coreana de textura ligera tipo gel que proporciona hidratación profunda y duradera sin sensación pesada, ideal para lograr una piel equilibrada, suave y luminosa. Versión de 30ml.", skin:"Ideal para pieles que necesitan hidratación sin pesadez.", ingredients:"Savia de abedul (birch juice) rica en minerales, aminoácidos y factores naturales de hidratación, ácido hialurónico, pantenol y niacinamida.", modo:"Aplicar como último paso de la rutina sobre el rostro limpio."},
  {key:"axisy-darkspot-glow-cream", name:"AXIS-Y Dark Spot Correcting Glow Cream", size:"50 ml", price:24550, retail:49000, img:"images/axisy-darkspot-glow-cream.jpg", benefit:"Crema hidratante iluminadora diseñada para reducir manchas oscuras, unificar el tono y fortalecer la barrera cutánea. Su textura ligera se absorbe rápidamente, dejando la piel suave, luminosa e hidratada sin sensación pesada.", skin:"Para todo tipo de piel, especialmente con manchas, tono desigual o piel opaca.", ingredients:"Niacinamida 5%, glutatión, escualano vegetal y ácido hialurónico.", modo:"Aplicar una cantidad adecuada sobre el rostro como último paso de la rutina. Usar mañana y/o noche."},
  {key:"dralthea-345-relief-cream", name:"Dr. Althea 345 Relief Cream", size:"50 ml", price:28500, retail:52000, img:"images/dralthea-345-relief-cream.jpg", benefit:"Crema calmante e hidratante que ayuda a reparar la barrera cutánea, reducir el enrojecimiento y aliviar la piel sensible.", skin:"Para todo tipo de piel, especialmente sensible, irritada o con la barrera cutánea dañada.", ingredients:"Niacinamida, pantenol, ceramida NP, extracto de nopal y extracto de lavanda.", modo:"Aplicar una cantidad adecuada sobre el rostro limpio como último paso de la rutina. Usar mañana y/o noche."},
]},
{ n:"07", title:"Brumas", items:[
  {key:"medicube-redclear-cica-bodymist", name:"Medicube Red Clear Cica Body Mist", size:"200 ml", price:25400, retail:45000, img:"images/medicube-redclear-cica-bodymist.jpg", benefit:"Es una bruma corporal tratante diseñada especialmente para acné corporal (espalda, pecho, hombros), que combina exfoliación química suave + ingredientes calmantes.", skin:"Ideal para piel con acné corporal, con textura irregular o con poros obstruidos.", ingredients:"AHA, BHA, PHA, niacinamida, tea tree y pantenol.", modo:"Aplicar después de la ducha."},
  {key:"medicube-kojic-turmeric-jellymist", name:"Medicube Kojic Acid Turmeric Vita Jelly Mist Serum", size:"100 ml", price:35100, retail:55000, img:"images/medicube-kojic-turmeric-jellymist.jpg", benefit:"Bruma sérum iluminadora que hidrata, ayuda a reducir manchas y aporta luminosidad al rostro con una textura ligera.", skin:"Para todo tipo de piel, especialmente con manchas, tono desigual o piel opaca.", ingredients:"Ácido kójico, cúrcuma, vitamina C y niacinamida.", modo:""},
  {key:"medicube-pdrn-collagen-jellymist", name:"Medicube PDRN Pink Collagen Glow Jelly Mist Serum", size:"100 ml", price:35350, retail:55000, img:"images/medicube-pdrn-collagen-jellymist.jpg", benefit:"Bruma sérum que hidrata, mejora la elasticidad y aporta un efecto glow inmediato con una textura ligera.", skin:"Para pieles especialmente secas, opacas o con pérdida de firmeza.", ingredients:"PDRN, colágeno, niacinamida y agua de colágeno.", modo:"Agitar antes de usar. Rociar sobre el rostro limpio a unos 20cm de distancia y dejar absorber. Puede utilizarse durante el día para refrescar la piel."},
  {key:"medicube-hypochlorous-facial-spray", name:"Medicube Hypochlorous Acid Daily Facial Spray", size:"125 ml", price:27600, retail:40000, img:"images/medicube-hypochlorous-facial-spray.jpg", benefit:"Bruma facial calmante que hidrata, reduce el enrojecimiento y ayuda a fortalecer la barrera de la piel.", skin:"Para todo tipo de piel, especialmente sensible, con tendencia al acné o irritada.", ingredients:"Ácido hipocloroso (HOCl), niacinamida al 2%, glicerina y agentes hidratantes.", modo:"Rociar sobre el rostro limpio a unos 20cm de distancia. Dejar secar al aire y continuar con tu rutina. Puede usarse durante el día para refrescar la piel."},
  {key:"dralthea-345-relief-cream-mist", name:"Dr. Althea 345 Relief Cream Mist", size:"60 ml", price:22550, retail:39000, img:"images/dralthea-345-relief-cream-mist.jpg", benefit:"Bruma hidratante que calma, refresca y fortalece la barrera cutánea, dejando la piel suave y equilibrada.", skin:"Para todo tipo de piel, especialmente sensible, seca o con irritación.", ingredients:"Pantenol, ceramidas, extracto de nopal, niacinamida, ácido hialurónico y extractos botánicos calmantes.", modo:"Rociar sobre el rostro limpio a 20-30cm de distancia y dejar absorber. Reaplicar durante el día cuando se necesite hidratación."},
]},
{ n:"08", title:"Contorno de ojos", items:[
  {key:"medicube-deeplifting-eye-standard", name:"Medicube Deep Lifting Peptide Eye Cream", size:"30 ml · estándar", price:30300, retail:49000, img:"images/medicube-deeplifting-eye-standard.jpg", benefit:"Diseñada para mejorar la firmeza y la elasticidad, suavizar líneas finas y aportar hidratación duradera. Devuelve vitalidad. Ayuda a reducir la apariencia de ojeras y arrugas mediante péptidos. Versión con una concentración estándar: hidrata y actúa para una elasticidad básica y cuidado para pieles sensibles.", skin:"Ideal para mantenimiento preventivo o pieles reactivas.", ingredients:"Péptidos, colágeno y ácido hialurónico.", modo:"Aplicar una pequeña cantidad alrededor de los ojos."},
  {key:"medicube-deeplifting-eye-concentrado", name:"Medicube Deep Lifting Peptide Eye Cream", size:"30 ml · concentrado", price:30300, retail:49000, img:"images/medicube-deeplifting-eye-concentrado.jpg", benefit:"Diseñada para mejorar la firmeza y la elasticidad, suavizar líneas finas y aportar hidratación duradera. Devuelve vitalidad. Ayuda a reducir la apariencia de ojeras y arrugas mediante péptidos. Versión más concentrada, con efecto 'lifting' más intensivo y tratamiento de arrugas profundas.", skin:"Ideal para líneas de expresión ya visibles.", ingredients:"Péptidos, colágeno y ácido hialurónico.", modo:"Aplicar una pequeña cantidad alrededor de los ojos."},
  {key:"celimax-retinal-shot-booster", name:"Celimax Retinal Shot Tightening Booster", size:"15 ml", price:24750, retail:45000, img:"images/celimax-retinal-shot-booster.jpg", benefit:"Tratamiento facial con retinal que ayuda a mejorar la firmeza de la piel, suavizar líneas de expresión y favorecer una apariencia más uniforme.", skin:"Para piel normal, seca, mixta, grasa y madura.", ingredients:"Retinal 0,1%, pantenol 1%, Matrixyl® 3000 al 3% y ceramidas.", modo:"Aplicar una pequeña cantidad sobre el rostro limpio durante la rutina nocturna, evitando el contorno de ojos y labios, y finalizar con una crema hidratante."},
]},
{ n:"09", title:"Rutina más completa", items:[
  {key:"anua-heartleaf-lha-peeling-gel", name:"Anua Heartleaf LHA Moisture Peeling Gel", size:"120 ml", price:20850, retail:35000, img:"images/anua-heartleaf-lha-peeling-gel.jpg", benefit:"Exfoliante facial suave tipo gommage (gel que 'forma bolitas') diseñado para eliminar células muertas sin irritar la piel. Limpia los poros, remueve células muertas y mejora la textura de la piel mientras mantiene la hidratación.", skin:"Ideal para pieles sensibles, mixta, grasa o con textura irregular.", ingredients:"Extracto de heartleaf (houttuynia), LHA y celulosa.", modo:"Después de la limpieza, antes del tónico."},
  {key:"roundlab-dokdo-lotion", name:"Round Lab 1025 Dokdo Lotion", size:"200 ml", price:18700, retail:35000, img:"images/roundlab-dokdo-lotion.jpg", benefit:"Loción hidratante ligera (tipo emulsión) que aporta hidratación profunda sin sensación pesada, ideal para mantener el equilibrio de la piel y reforzar la barrera cutánea.", skin:"Para todo tipo de piel.", ingredients:"Agua marina profunda de Dokdo, pantenol y alantoína.", modo:"Después del tónico, antes de la crema hidratante, o puede reemplazarla en caso de piel mixta/grasa."},
  {key:"anua-heartleaf70-daily-relief-lotion", name:"Anua Heartleaf 70% Daily Relief Lotion", size:"200 ml", price:25100, retail:45000, img:"images/anua-heartleaf70-daily-relief-lotion.jpg", benefit:"Exfoliante físico muy delicado que actúa arrastrando células muertas, sebo y suciedad acumulada, sin necesidad de partículas abrasivas. Estas 'bolitas' se forman por la celulosa del producto, que se adhiere a las impurezas para retirarlas suavemente.", skin:"Ideal para piel sensible o irritada, piel mixta a grasa, con acné o rojeces.", ingredients:"70% extracto de heartleaf, pantenol y ácido hialurónico.", modo:"Aplicar cantidad moderada sobre rostro limpio después del tónico o sérum. Masajear suavemente hasta su total absorción."},
  {key:"medicube-centellascar-ointment", name:"Medicube Centellascar Ointment", size:"15 ml", price:18150, retail:25000, img:"images/medicube-centellascar-ointment.jpg", benefit:"Pomada reparadora intensiva con centella asiática que calma, regenera y fortalece la barrera cutánea, ayudando a reducir rojeces, inflamación, marcas post-acné e irritaciones mientras mejora la textura de la piel.", skin:"Todo tipo de piel, especialmente sensible o con imperfecciones.", ingredients:"Centella asiática, madecasósido y agentes reparadores.", modo:"Aplicar una pequeña cantidad sobre zonas dañadas o con marcas después de la rutina."},
]},
];
